
# /Users/justinjiang/Desktop/vistrans/rasmus/treelib_tab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\xd1\x94\xeb\xec\x1e\x9bw\xc0\xc8\xcc5\x85\xedL\x98Q'
    
_lr_action_items = {'(':([0,3,11,],[3,3,3,]),'NAME':([0,3,10,11,],[4,4,12,4,]),'DATA':([0,3,4,10,11,12,],[5,5,9,13,5,15,]),'$end':([1,6,],[0,-1,]),';':([2,4,5,9,10,12,13,15,],[6,-7,-8,-6,-5,-3,-4,-2,]),',':([4,5,8,9,10,12,13,15,],[-7,-8,11,-6,-5,-3,-4,-2,]),')':([4,5,7,8,9,10,12,13,14,15,],[-7,-8,10,-10,-6,-5,-3,-4,-9,-2,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'tree':([0,],[1,]),'subtree':([0,3,11,],[2,8,8,]),'branch_set':([3,11,],[7,14,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> tree","S'",1,None,None,None),
  ('tree -> subtree ;','tree',2,'p_tree','/Users/justinjiang/Desktop/vistrans/rasmus/treelib_parser.py',41),
  ('subtree -> ( branch_set ) NAME DATA','subtree',5,'p_subtree','/Users/justinjiang/Desktop/vistrans/rasmus/treelib_parser.py',47),
  ('subtree -> ( branch_set ) NAME','subtree',4,'p_subtree','/Users/justinjiang/Desktop/vistrans/rasmus/treelib_parser.py',48),
  ('subtree -> ( branch_set ) DATA','subtree',4,'p_subtree','/Users/justinjiang/Desktop/vistrans/rasmus/treelib_parser.py',49),
  ('subtree -> ( branch_set )','subtree',3,'p_subtree','/Users/justinjiang/Desktop/vistrans/rasmus/treelib_parser.py',50),
  ('subtree -> NAME DATA','subtree',2,'p_subtree','/Users/justinjiang/Desktop/vistrans/rasmus/treelib_parser.py',51),
  ('subtree -> NAME','subtree',1,'p_subtree','/Users/justinjiang/Desktop/vistrans/rasmus/treelib_parser.py',52),
  ('subtree -> DATA','subtree',1,'p_subtree','/Users/justinjiang/Desktop/vistrans/rasmus/treelib_parser.py',53),
  ('branch_set -> subtree , branch_set','branch_set',3,'p_branch_set','/Users/justinjiang/Desktop/vistrans/rasmus/treelib_parser.py',71),
  ('branch_set -> subtree','branch_set',1,'p_branch_set','/Users/justinjiang/Desktop/vistrans/rasmus/treelib_parser.py',72),
]
